### ISSUE TITLE
How can i exclude ie11

### ISSUE THREAD

**Issue by cimt** [electerious/basicScroll#50]
How can i exclude ie11.
Browser detection to exclude the script does not work, always the **syntax error**!
I'm testing on win7 / IE11

It doesn't have to work... simply exclude ie11!

grateful for any help

**Comment by electerious** [comment]
basicScroll shouldn't throw any errors when you use the [transpiled version](https://github.com/electerious/basicScroll/tree/master/dist) and install all [required polyfills](https://github.com/electerious/basicScroll#requirements). Just make sure you aren't importing the untranspiled version as this one includes syntax that won't work in IE11.

This way you will get a working version of basicScroll (but without support for CSS variables because of IE11).
